//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConversorRef
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConversorRef.IConversionService")]
    public interface IConversionService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/CentimetersToFeet", ReplyAction="http://tempuri.org/IConversionService/CentimetersToFeetResponse")]
        System.Threading.Tasks.Task<double> CentimetersToFeetAsync(double centimeters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/FeetToCentimeters", ReplyAction="http://tempuri.org/IConversionService/FeetToCentimetersResponse")]
        System.Threading.Tasks.Task<double> FeetToCentimetersAsync(double feet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/MetersToYards", ReplyAction="http://tempuri.org/IConversionService/MetersToYardsResponse")]
        System.Threading.Tasks.Task<double> MetersToYardsAsync(double meters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/YardsToMeters", ReplyAction="http://tempuri.org/IConversionService/YardsToMetersResponse")]
        System.Threading.Tasks.Task<double> YardsToMetersAsync(double yards);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/InchesToCentimeters", ReplyAction="http://tempuri.org/IConversionService/InchesToCentimetersResponse")]
        System.Threading.Tasks.Task<double> InchesToCentimetersAsync(double inches);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/CentimetersToInches", ReplyAction="http://tempuri.org/IConversionService/CentimetersToInchesResponse")]
        System.Threading.Tasks.Task<double> CentimetersToInchesAsync(double centimeters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/KilogramsToPounds", ReplyAction="http://tempuri.org/IConversionService/KilogramsToPoundsResponse")]
        System.Threading.Tasks.Task<double> KilogramsToPoundsAsync(double kilograms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/PoundsToKilograms", ReplyAction="http://tempuri.org/IConversionService/PoundsToKilogramsResponse")]
        System.Threading.Tasks.Task<double> PoundsToKilogramsAsync(double pounds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/GramsToOunces", ReplyAction="http://tempuri.org/IConversionService/GramsToOuncesResponse")]
        System.Threading.Tasks.Task<double> GramsToOuncesAsync(double grams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/OuncesToGrams", ReplyAction="http://tempuri.org/IConversionService/OuncesToGramsResponse")]
        System.Threading.Tasks.Task<double> OuncesToGramsAsync(double ounces);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/CelsiusToFahrenheit", ReplyAction="http://tempuri.org/IConversionService/CelsiusToFahrenheitResponse")]
        System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/FahrenheitToCelsius", ReplyAction="http://tempuri.org/IConversionService/FahrenheitToCelsiusResponse")]
        System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/CelsiusToKelvin", ReplyAction="http://tempuri.org/IConversionService/CelsiusToKelvinResponse")]
        System.Threading.Tasks.Task<double> CelsiusToKelvinAsync(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/KelvinToCelsius", ReplyAction="http://tempuri.org/IConversionService/KelvinToCelsiusResponse")]
        System.Threading.Tasks.Task<double> KelvinToCelsiusAsync(double kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/FahrenheitToKelvin", ReplyAction="http://tempuri.org/IConversionService/FahrenheitToKelvinResponse")]
        System.Threading.Tasks.Task<double> FahrenheitToKelvinAsync(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/KelvinToFahrenheit", ReplyAction="http://tempuri.org/IConversionService/KelvinToFahrenheitResponse")]
        System.Threading.Tasks.Task<double> KelvinToFahrenheitAsync(double kelvin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IConversionServiceChannel : ConversorRef.IConversionService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ConversionServiceClient : System.ServiceModel.ClientBase<ConversorRef.IConversionService>, ConversorRef.IConversionService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ConversionServiceClient() : 
                base(ConversionServiceClient.GetDefaultBinding(), ConversionServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IConversionService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversionServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ConversionServiceClient.GetBindingForEndpoint(endpointConfiguration), ConversionServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversionServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ConversionServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversionServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ConversionServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<double> CentimetersToFeetAsync(double centimeters)
        {
            return base.Channel.CentimetersToFeetAsync(centimeters);
        }
        
        public System.Threading.Tasks.Task<double> FeetToCentimetersAsync(double feet)
        {
            return base.Channel.FeetToCentimetersAsync(feet);
        }
        
        public System.Threading.Tasks.Task<double> MetersToYardsAsync(double meters)
        {
            return base.Channel.MetersToYardsAsync(meters);
        }
        
        public System.Threading.Tasks.Task<double> YardsToMetersAsync(double yards)
        {
            return base.Channel.YardsToMetersAsync(yards);
        }
        
        public System.Threading.Tasks.Task<double> InchesToCentimetersAsync(double inches)
        {
            return base.Channel.InchesToCentimetersAsync(inches);
        }
        
        public System.Threading.Tasks.Task<double> CentimetersToInchesAsync(double centimeters)
        {
            return base.Channel.CentimetersToInchesAsync(centimeters);
        }
        
        public System.Threading.Tasks.Task<double> KilogramsToPoundsAsync(double kilograms)
        {
            return base.Channel.KilogramsToPoundsAsync(kilograms);
        }
        
        public System.Threading.Tasks.Task<double> PoundsToKilogramsAsync(double pounds)
        {
            return base.Channel.PoundsToKilogramsAsync(pounds);
        }
        
        public System.Threading.Tasks.Task<double> GramsToOuncesAsync(double grams)
        {
            return base.Channel.GramsToOuncesAsync(grams);
        }
        
        public System.Threading.Tasks.Task<double> OuncesToGramsAsync(double ounces)
        {
            return base.Channel.OuncesToGramsAsync(ounces);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double celsius)
        {
            return base.Channel.CelsiusToFahrenheitAsync(celsius);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double fahrenheit)
        {
            return base.Channel.FahrenheitToCelsiusAsync(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusToKelvinAsync(double celsius)
        {
            return base.Channel.CelsiusToKelvinAsync(celsius);
        }
        
        public System.Threading.Tasks.Task<double> KelvinToCelsiusAsync(double kelvin)
        {
            return base.Channel.KelvinToCelsiusAsync(kelvin);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitToKelvinAsync(double fahrenheit)
        {
            return base.Channel.FahrenheitToKelvinAsync(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<double> KelvinToFahrenheitAsync(double kelvin)
        {
            return base.Channel.KelvinToFahrenheitAsync(kelvin);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConversionService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConversionService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:52091/ec.edu.espe.monster.ws/ConversionService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ConversionServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IConversionService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ConversionServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IConversionService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IConversionService,
        }
    }
}
